# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20160326_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='logo',
            field=models.ImageField(upload_to='forum/media'),
        ),
    ]
