# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20160326_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='colnum',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
