# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_thread_parsed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='uses',
            field=models.BigIntegerField(),
        ),
    ]
