# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 08:27
from __future__ import unicode_literals

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20160408_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='logo',
            field=models.ImageField(upload_to=forum.models.get_unique_path),
        ),
    ]
