# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20160408_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
