# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_auto_20160408_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_ip', models.CharField(default='127.0.0.1', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='127.0.0.1', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author_ip',
            field=models.CharField(default='127.0.0.1', max_length=100),
        ),
    ]
