# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_auto_20160408_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_ip',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
