# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_auto_20160412_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='author_ip',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
