# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_thread_author_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
