# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_auto_20160416_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
