# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0040_auto_20160416_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.ManyToManyField(blank=True, to='forum.Comment'),
        ),
    ]
