# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 20:52
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_thread_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='threads',
            field=models.ManyToManyField(blank=True, to='blog.Thread'),
        ),
    ]
