# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160327_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='parent',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
