# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_thread_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('uses', models.BigIntegerField(verbose_name=0)),
                ('parent', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='colnum',
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
