# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160404_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
