# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_thread_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='parsed_tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
