# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_thread_time_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='body',
            new_name='text',
        ),
    ]
