# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 08:48
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160408_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thumb',
            field=models.ImageField(default='f', upload_to=blog.models.get_unique_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='thumb',
            field=models.ImageField(default=1, upload_to=blog.models.get_unique_path),
            preserve_default=False,
        ),
    ]
