# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20160408_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thumb',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thumb',
            new_name='image',
        ),
    ]
