# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20160408_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='unknown', max_length=100)),
                ('last_request', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='users',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='address',
            field=models.CharField(default='u', max_length=100),
        ),
    ]
