# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20160410_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.AddField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(blank=True, to='blog.UserIp'),
        ),
    ]
