# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20160412_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='last_request',
            field=models.DateTimeField(default=0),
        ),
    ]
