# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20160412_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 18, 9, 21, 442911)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='last_request',
            field=models.DateTimeField(default=None),
        ),
    ]
